= Intro to ClojureScript
:author:    Tim Gilbert
:source-highlighter: pygments
:backend: slidy
:max-width: 45em
:data-uri:
:icons:

== Agenda
- Lisp Refresher
- Clojure
- ClojureScript
- More ClojureScript
- Questions and Answers

== An Abbreviated History of Lisp Dialects
[role="incremental"]
* LISP 1.0, 1958
** LISt Processor, invented by John McCarthy

* Scheme, 1975
** Minimalist, functional variant
** First dialect to implement tail-call optimization

* Common Lisp, 1984
** Unified different dialects into de facto standard

* ANSI Standard Common Lisp, 1994
** CLOS: Common Lisp Object System

* Clojure, 2007
** Functional (emphasis on immutability)
** Tight integration with Java virtual machine
** ClojureScript: Clojure-to-Javascript compiler

== Lisp: Basics

- Basic primitives: numbers, strings, boolean, more
- Top-level items are "forms" (eg, lists input to the repl)
- When a form is evaluated, the first element is a function
  and the rest are arguments

[source,common-lisp]
.Example
------------------------------------------------------
(+ 3 4 5 6)                     ; => 18
(/ (+ 3 4 5 6) 2)               ; => 9
(= 9 (/ (+ 3 4 5 6) 2))         ; => T
(= 7 (/ (+ 3 4 5 6) 2))         ; => NIL
(string-upcase "hello")         ; => "HELLO"
(string-concat (string-upcase "hello,") "there")
                                ; => "HELLO,there"
------------------------------------------------------

== Lisp: List Processing

- The quote macro `'` prevents items from being evaluated
- The function `(list x y z)` produces the list `(x y z)`
- `car` and `cdr` are names derived from from the names of
  registers on the IBM 704

[source,common-lisp]
.Example
------------------------------------------------------
'(1 2 3 4)                      ; => (1 2 3 4)
(list 1 (+ 1 1) 3 4)            ; => (1 2 3 4)
'(1 (+ 1 1) 3 4)                ; => (1 (+ 1 1) 3 4)
(car '(1 2 3 4))                ; => 1
;; Equivalent: (first '(1 2 3 4))
(cdr '(1 2 3 4))                ; => (2 3 4)
;; Equivalent: (rest '(1 2 3 4))
(cadadr '(1 (20 30) 4 5 6))     ; => 30
------------------------------------------------------

== Lisp: Functions

- Functions are first-class (can be passed as arguments, etc)
- The usual functional programming suspects exist (`map`, etc)
- Common lisp needs sharp-quote (`#'`) for function quoting
- Lambda expressions exist (and must also be sharp-quoted)

[source,common-lisp]
.Example
------------------------------------------------------
(defun square (x)
  (* x x))
(square 4)                      ; => 9
(mapcar #'square '(1 2 3 4 5))  ; => (1 4 9 16 25)
(mapcar #'(lambda (x) (+ x 5))
        '(10 20 30))            ; => (15 25 35)
------------------------------------------------------

== Lisp: Recursion

- Lisp includes both functional and imperative constructs
- Lists lend themselves well to recursive processing

[source,common-lisp]
.Example
------------------------------------------------------
(defun sum-list (input)
  (if (null input)
      0
      (+ (car input)
         (sum-list (cdr input)))))

(sum-list '(3 4 5))          ; => 12
(sum-list '())               ; => 0
------------------------------------------------------

== Lisp: Macros

- Lisp is homoiconic; its programs are comprised of lists
- That lends itself to code which manipulates or produces other code
- Macros can be used to invent your own control structures, by controlling
  what elements are evaluated

[source,common-lisp]
.Example
------------------------------------------------------
(defmacro if-not (condition true-form false-form)
  `(if (not ,condition) ,true-form ,false-form)))

(if-not (= 3 4) "true-value" "false-value")
; => "true-value"
(macroexpand-1 '(if-not (= 3 4) "true-value" "false-value"))
' => (IF (NOT (= 3 4)) "true-value" "false-value")
------------------------------------------------------

== Clojure: Features

[role="incremental"]
* Lisp, but not Common Lisp
** Standard library written from the ground up
** Syntax sugar for data structures (maps, sets, vectors)

* Specifically targeted to the JVM
** Compiles to JVM bytecode
** Good interoperability with Java libraries

* Concurrency primitives in the standard library
** STM: agents, refs, atoms.

* Prefers purely-functional programming styles and idioms
** Immutable data structures
** Imperative style is still possible, but de-emphasized

== Clojure: Code

[source,clojure]
.Example
------------------------------------------------------
(defn indexable? [word]
  (> (count word) 2)
(indexable? "to")               ; => false
(indexable? "clojure")          ; => true
(filter indexable? '("I" "am" "writing" "in" "clojure"))
                                ; => ("writing" "clojure")
------------------------------------------------------

- Parameter list: `[word]`. Square brackets construct a _vector_ (list
  with good random-access performance).
- No need for sharp-quotes; `indexable?` by itself evaluates to the
  function object

== Clojure: Maps

== ClojureScript

== That's it

Questions?